services:
  - type: web
    name: toko-pakde-kuwat
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_NAME
        value: Toko Pakde Kuwat
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: ACCOUNT_MANAGEMENT_PASSWORD
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database